# Run stage (Build is done by GitHub Actions)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# GitHub Actions가 전송해준 jar 파일을 컨테이너 내부로 복사
COPY build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
