spring.application.name=sleepy-backend
server.port = 8383

spring.datasource.url=jdbc:mysql://localhost:3306/sleepy
spring.datasource.username=root
spring.datasource.password=Ap513147!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.SECRET_KEY=sleepy-project-jwt-secret-key-1234567890
jwt.expiration=604800000

logging.level.org.springframework.security=TRACE

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Multipart Upload Limits (Enable large images/videos up to 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS S3 Settings
aws.s3.bucket=sleepy-media
aws.s3.region=ap-northeast-2
spring.cloud.aws.credentials.access-key=YOUR_AWS_ACCESS_KEY
spring.cloud.aws.credentials.secret-key=YOUR_AWS_SECRET_KEY