ALTER TABLE report MODIFY COLUMN target_type ENUM('POST', 'COMMENT', 'PRODUCT', 'REVIEW') NOT NULL;
ALTER TABLE notification MODIFY COLUMN type ENUM('NEW_COMMENT', 'NEW_LIKE', 'SYSTEM_ALERT', 'NEW_MESSAGE', 'WISHLIST_UPDATE', 'SELLER_APPROVAL', 'SELLER_REJECTED', 'NEW_REVIEW', 'NEW_SELLER_APPLICATION', 'NEW_REPORT', 'NEW_INQUIRY', 'INQUIRY_ANSWERED') NOT NULL;
